package com.foodapp.model;

/**
 * POJO class for the "locations" table.
 * Represents a saved delivery address for a user (e.g. Home, Work).
 * No DB logic here - that goes in LocationDAO later.
 */
public class Location {

    // ---- fields (match column names/types of locations table) ----
    private int locationId;      // locations.location_id
    private int userId;          // locations.user_id (foreign key to users table)
    private String label;        // locations.label (e.g. "HOME", "WORK", "OTHER")
    private String addressLine;  // locations.address_line
    private String city;         // locations.city
    private String pincode;      // locations.pincode
    private boolean isDefault;   // locations.is_default (true = auto-selected at checkout)

    // ------------------------------------------------------------
    // Constructors
    // ------------------------------------------------------------

    // Empty constructor - required for frameworks/servlets to create
    // an object first and fill values later using setters
    public Location() {
    }

    // Use this when INSERTING a new location
    // (locationId is generated by the DB, so not needed here)
    public Location(int userId, String label, String addressLine, String city,
                     String pincode, boolean isDefault) {
        this.userId = userId;
        this.label = label;
        this.addressLine = addressLine;
        this.city = city;
        this.pincode = pincode;
        this.isDefault = isDefault;
    }

    // Use this when READING a location row back from the DB (ResultSet)
    public Location(int locationId, int userId, String label, String addressLine,
                     String city, String pincode, boolean isDefault) {
        this.locationId = locationId;
        this.userId = userId;
        this.label = label;
        this.addressLine = addressLine;
        this.city = city;
        this.pincode = pincode;
        this.isDefault = isDefault;
    }

    // ------------------------------------------------------------
    // Getters and Setters
    // ------------------------------------------------------------

    public int getLocationId() {
        return locationId;
    }

    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getAddressLine() {
        return addressLine;
    }

    public void setAddressLine(String addressLine) {
        this.addressLine = addressLine;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPincode() {
        return pincode;
    }

    public void setPincode(String pincode) {
        this.pincode = pincode;
    }

    public boolean isDefault() {
        return isDefault;
    }

    public void setDefault(boolean isDefault) {
        this.isDefault = isDefault;
    }

    // ------------------------------------------------------------
    // toString() - handy for debugging/console logs
    // ------------------------------------------------------------
    @Override
    public String toString() {
        return "Location{" +
                "locationId=" + locationId +
                ", userId=" + userId +
                ", label='" + label + '\'' +
                ", addressLine='" + addressLine + '\'' +
                ", city='" + city + '\'' +
                ", pincode='" + pincode + '\'' +
                ", isDefault=" + isDefault +
                '}';
    }
}