package com.foodapp.model;

/**
 * POJO class for the "order_items" table.
 * Each OrderItem is a single line item inside an Order
 * (like one row in a shopping cart: which menu item, how many, at what price).
 * No DB logic here - that goes in OrderItemDAO later.
 */
public class OrderItem {

    // ---- fields (match column names/types of order_items table) ----
    private int orderItemId;   // order_items.order_item_id
    private int orderId;       // order_items.order_id (foreign key to orders table)
    private int itemId;        // order_items.item_id (foreign key to menu table)
    private int quantity;      // order_items.quantity
    private double price;      // order_items.price (price AT THE TIME of order, not current menu price)

    // ------------------------------------------------------------
    // Constructors
    // ------------------------------------------------------------

    // Empty constructor - required for frameworks/servlets to create
    // an object first and fill values later using setters
    public OrderItem() {
    }

    // Use this when INSERTING a new order item
    // (orderItemId is generated by the DB, so not needed here)
    public OrderItem(int orderId, int itemId, int quantity, double price) {
        this.orderId = orderId;
        this.itemId = itemId;
        this.quantity = quantity;
        this.price = price;
    }

    // Use this when READING an order_item row back from the DB (ResultSet)
    public OrderItem(int orderItemId, int orderId, int itemId, int quantity, double price) {
        this.orderItemId = orderItemId;
        this.orderId = orderId;
        this.itemId = itemId;
        this.quantity = quantity;
        this.price = price;
    }

    // ------------------------------------------------------------
    // Getters and Setters
    // ------------------------------------------------------------

    public int getOrderItemId() {
        return orderItemId;
    }

    public void setOrderItemId(int orderItemId) {
        this.orderItemId = orderItemId;
    }

    public int getOrderId() {
        return orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    public int getItemId() {
        return itemId;
    }

    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    // ------------------------------------------------------------
    // toString() - handy for debugging/console logs
    // ------------------------------------------------------------
    @Override
    public String toString() {
        return "OrderItem{" +
                "orderItemId=" + orderItemId +
                ", orderId=" + orderId +
                ", itemId=" + itemId +
                ", quantity=" + quantity +
                ", price=" + price +
                '}';
    }
}