package com.foodapp.model;

import java.sql.Timestamp;

/**
 * POJO class for the "orders" table.
 * One Order = one checkout by one user from one restaurant.
 * No DB logic here - that goes in OrderDAO later.
 */
public class Order {

    // ---- fields (match column names/types of orders table) ----
    private int orderId;           // orders.order_id
    private int userId;            // orders.user_id (foreign key to users table)
    private int restaurantId;      // orders.restaurant_id (foreign key to restaurants table)
    private double totalAmount;    // orders.total_amount
    private String status;         // orders.status ('PLACED' / 'DELIVERED' / 'CANCELLED')
    private String imageUrl;       // orders.image_url
    private Timestamp orderDate;   // orders.order_date

    // ------------------------------------------------------------
    // Constructors
    // ------------------------------------------------------------

    // Empty constructor - required for frameworks/servlets to create
    // an object first and fill values later using setters
    public Order() {
    }

    // Use this when INSERTING a new order
    // (orderId and orderDate are generated by the DB, so not needed here)
    public Order(int userId, int restaurantId, double totalAmount, String status, String imageUrl) {
        this.userId = userId;
        this.restaurantId = restaurantId;
        this.totalAmount = totalAmount;
        this.status = status;
        this.imageUrl = imageUrl;
    }

    // Use this when READING an order row back from the DB (ResultSet)
    public Order(int orderId, int userId, int restaurantId, double totalAmount,
                 String status, String imageUrl, Timestamp orderDate) {
        this.orderId = orderId;
        this.userId = userId;
        this.restaurantId = restaurantId;
        this.totalAmount = totalAmount;
        this.status = status;
        this.imageUrl = imageUrl;
        this.orderDate = orderDate;
    }

    // ------------------------------------------------------------
    // Getters and Setters
    // ------------------------------------------------------------

    public int getOrderId() {
        return orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getRestaurantId() {
        return restaurantId;
    }

    public void setRestaurantId(int restaurantId) {
        this.restaurantId = restaurantId;
    }

    public double getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public Timestamp getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Timestamp orderDate) {
        this.orderDate = orderDate;
    }

    // ------------------------------------------------------------
    // toString() - handy for debugging/console logs
    // ------------------------------------------------------------
    @Override
    public String toString() {
        return "Order{" +
                "orderId=" + orderId +
                ", userId=" + userId +
                ", restaurantId=" + restaurantId +
                ", totalAmount=" + totalAmount +
                ", status='" + status + '\'' +
                ", imageUrl='" + imageUrl + '\'' +
                ", orderDate=" + orderDate +
                '}';
    }
}
