package com.foodapp.model;

/**
 * POJO class for the "ratings" table.
 * One Rating = one user's star rating (1-5) + comment for one restaurant.
 * No DB logic here - that goes in RatingDAO later.
 */
public class Rating {

    // ---- fields (match column names/types of ratings table) ----
    private int ratingId;       // ratings.rating_id
    private int userId;         // ratings.user_id (foreign key to users table)
    private int restaurantId;   // ratings.restaurant_id (foreign key to restaurants table)
    private int rating;         // ratings.rating (value between 1 and 5, enforced by DB CHECK constraint)
    private String comment;     // ratings.comment

    // ------------------------------------------------------------
    // Constructors
    // ------------------------------------------------------------

    // Empty constructor - required for frameworks/servlets to create
    // an object first and fill values later using setters
    public Rating() {
    }

    // Use this when INSERTING a new rating
    // (ratingId is generated by the DB, so not needed here)
    public Rating(int userId, int restaurantId, int rating, String comment) {
        this.userId = userId;
        this.restaurantId = restaurantId;
        this.rating = rating;
        this.comment = comment;
    }

    // Use this when READING a rating row back from the DB (ResultSet)
    public Rating(int ratingId, int userId, int restaurantId, int rating, String comment) {
        this.ratingId = ratingId;
        this.userId = userId;
        this.restaurantId = restaurantId;
        this.rating = rating;
        this.comment = comment;
    }

    // ------------------------------------------------------------
    // Getters and Setters
    // ------------------------------------------------------------

    public int getRatingId() {
        return ratingId;
    }

    public void setRatingId(int ratingId) {
        this.ratingId = ratingId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getRestaurantId() {
        return restaurantId;
    }

    public void setRestaurantId(int restaurantId) {
        this.restaurantId = restaurantId;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    // ------------------------------------------------------------
    // toString() - handy for debugging/console logs
    // ------------------------------------------------------------
    @Override
    public String toString() {
        return "Rating{" +
                "ratingId=" + ratingId +
                ", userId=" + userId +
                ", restaurantId=" + restaurantId +
                ", rating=" + rating +
                ", comment='" + comment + '\'' +
                '}';
    }
}