package com.foodapp.model;   // change this to match your actual package name

import java.sql.Timestamp;

/**
 * POJO class for the "restaurants" table.
 * Just holds data - no DB logic here (that goes in RestaurantDAO later).
 */
public class Restaurant {

    // ---- fields (match column names/types of restaurants table) ----
    private int restaurantId;      // restaurants.restaurant_id
    private String name;           // restaurants.name
    private String address;        // restaurants.address
    private String phone;          // restaurants.phone
    private double rating;         // restaurants.rating
    private String imageUrl;       // restaurants.image_url  (path to image file, not the image itself)
    private Timestamp createdAt;   // restaurants.created_at

    // ------------------------------------------------------------
    // Constructors
    // ------------------------------------------------------------

    // Empty constructor - required for frameworks/servlets to create
    // an object first and fill values later using setters
    public Restaurant() {
    }

    // Use this when INSERTING a new restaurant
    // (id and created_at are generated by the DB, so they're not needed here)
    public Restaurant(String name, String address, String phone, double rating, String imageUrl) {
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.rating = rating;
        this.imageUrl = imageUrl;
    }

    // Use this when READING a restaurant row back from the DB (ResultSet)
    public Restaurant(int restaurantId, String name, String address, String phone,
                       double rating, String imageUrl, Timestamp createdAt) {
        this.restaurantId = restaurantId;
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.rating = rating;
        this.imageUrl = imageUrl;
        this.createdAt = createdAt;
    }

    // ------------------------------------------------------------
    // Getters and Setters
    // ------------------------------------------------------------

    public int getRestaurantId() {
        return restaurantId;
    }

    public void setRestaurantId(int restaurantId) {
        this.restaurantId = restaurantId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public double getRating() {
        return rating;
    }

    public void setRating(double rating) {
        this.rating = rating;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    // ------------------------------------------------------------
    // toString() - handy for debugging/console logs
    // ------------------------------------------------------------
    @Override
    public String toString() {
        return "Restaurant{" +
                "restaurantId=" + restaurantId +
                ", name='" + name + '\'' +
                ", address='" + address + '\'' +
                ", phone='" + phone + '\'' +
                ", rating=" + rating +
                ", imageUrl='" + imageUrl + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}